server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: false
  forced_hosts:
    archi.breakerland.fr: archi
    archi.horyzon.eu: archi
    breakerland.fr: survie
    mc.breakerland.fr: survie
    mc.horyzon.eu: hub
    crea.breakerland.fr: creatif
    crea.horyzon.eu: creatif
    dev.breakerland.fr: dev
    tcf.horyzon.eu: tcf
    xyloria.horyzon.eu: xyloria
    atonium.horyzon.eu: skyblock
    sky.horyzon.eu: skyblock
    sky.breakerland.fr: skyblock
    survie.breakerland.fr: survie
  host: $public_address:$proxy_port
  max_players: 60
  motd: '&7───── Bienvenue sur &3&lBreakerland &7! ─────    &2│ &61.16 &2│ $ &2│ &cGrades &2│ &fLands &2│ &cMétiers &2│ &fPets &2│'
  ping_passthrough: true
  priorities:
  - survie
  - creatif
  proxy_protocol: false
  query_enabled: true
  query_port: $proxy_query
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.send
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.find
  - bungeecord.command.reload
log_pings: false
connection_throttle_limit: 5
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  '7e6900e7-ad36-4c5c-9193-429a54f6d09f':
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: a727f6a7-8fc5-4b55-88c5-3c035821e1cb
online_mode: false
forge_support: true
disabled_commands: []
servers:
  $server_name_hub:
    address: $local_address:$server_port_hub
    motd: '&7───── Bienvenue sur &3&lHoryzon &7! ─────                       &2│ &6Breakerland &2| &6Herablex &2│'
    restricted: true
  $server_name_auth:
    address: $local_address:$server_port_auth
    motd: '&7───── Bienvenue sur &3&lHoryzon &7! ─────                       &2│ &6Breakerland &2| &6Herablex &2│'
    restricted: true
  $server_name_survie:
    address: $local_address:$server_port_survie
    motd: '&7───── Bienvenue sur &3&lBreakerland &7! ─────    &2│ &61.16 &2│ $ &2│ &cGrades &2│ &fLands &2│ &cMétiers &2│ &fPets &2│'
    restricted: false
  $server_name_creatif:
    address: $local_address:$server_port_creatif
    motd: '&7───── Bienvenue sur &3&lBreakerland &7! ─────    &2│ &61.16 &2│ $ &2│ &cCreatif &2│ &fPlots &2│ &cWorldEdit &2│ &fArmorstand &2│'
    restricted: false
  $server_name_event:
    address: $local_address:$server_port_event
    motd: '&7──── Bienvenue sur &3&lBreakerland Event &7! ────'
    restricted: false
  $server_name_archi:
    address: $local_address:$server_port_archi
    motd: '&7───── Bienvenue sur &3&lBreakerland &7! ─────    &2│ &61.16 &2│ $ &2│ &cGrades &2│ &fLands &2│ &cMétiers &2│ &fPets &2│'
    restricted: true
  $server_name_dev:
    address: $local_address:$server_port_dev
    motd: '&7──── Bienvenue sur &3&lBreakerland Dev &7! ────'
    restricted: true
  $server_name_tcf:
    address: $remote_address_02:$server_port_tcf
    motd: '&7──── Bienvenue sur &3&lHoryzon TCF &7! ────'
    restricted: true
  $server_name_skyblock:
    address: $remote_address_02:$server_port_skyblock
    motd: '&7──── Bienvenue sur &3&lAtonium &7! ────'
    restricted: false
  $server_name_xyloria:
    address: $remote_address_02:$server_port_xyloria
    motd: '&7──── Bienvenue sur &3&lXyloria &7! ────'
    restricted: true